trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:

- task: PowerShell@2
  displayName: 'GitVersion'
  inputs:
    targetType: 'inline'
    script: 'gitversion /l console /output buildserver /updateAssemblyInfo'

- task: DotNetCoreCLI@2
  displayName: 'Build RX.Nyss.Web and RX.Nyss.Data.MigrationApp'
  inputs:
    command: 'build'
    projects: |
      src/RX.Nyss.Web/RX.Nyss.Web.csproj 
      src/RX.Nyss.Data.MigrationApp/RX.Nyss.Data.MigrationApp.csproj
    arguments: '-c Release -r win-x86 "/p:Version=$(GitVersion.MajorMinorPatch)"'

- task: DotNetCoreCLI@2
  displayName: 'Build RX.Nyss.FuncApp'
  inputs:
    projects: 'src/RX.Nyss.FuncApp/RX.Nyss.FuncApp.csproj'
    arguments: '-c Release "/p:Version=$(GitVersion.MajorMinorPatch)"' # Azure Functions do not support -r parameter

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: test
    projects: './tests/Rx.Nyss.Web.Tests/Rx.Nyss.Web.Tests.csproj'
    arguments: '--no-build'

- task: DotNetCoreCLI@2
  displayName: 'Publish RX.Nyss.Web'
  inputs:
    command: publish
    publishWebProjects: false
    arguments: './src/RX.Nyss.Web/RX.Nyss.Web.csproj -c Release -r win-x86 --self-contained --no-build /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishReadyToRunShowWarnings=true -o "$(Build.ArtifactStagingDirectory)/webapp"'
    zipAfterPublish: true
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  displayName: 'Publish RX.Nyss.FuncApp'
  inputs:
    command: publish
    publishWebProjects: false
    arguments: './src/RX.Nyss.FuncApp/RX.Nyss.FuncApp.csproj -c Release --no-build -o "$(Build.ArtifactStagingDirectory)/funcapp" '
    zipAfterPublish: true
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  displayName: 'Publish RX.Nyss.Data.MigrationApp'
  inputs:
    command: publish
    publishWebProjects: false
    arguments: './src/RX.Nyss.Data.MigrationApp/RX.Nyss.Data.MigrationApp.csproj -c Release -r win-x86 --self-contained --no-build -o "$(Build.ArtifactStagingDirectory)/migrationapp"'
    zipAfterPublish: false
    modifyOutputPath: false

- task: CopyFiles@2
  inputs:
    SourceFolder: 'Infrastructure'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Infrastructure'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
